spring:
  datasource:
    url: jdbc:mysql://101.34.56.11/weather?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 101.34.56.11
    port: 6379
    database: 2
    timeout: 5000
    password: eqaxf241

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atigu.weather.model

weather:
  url: https://kr564rdk3p.re.qweatherapi.com
  kid: CAGXUXW5FE
  privateKey: MC4CAQAwBQYDK2VwBCIEIDS73jfImemmENYW3ChFZxRbhMkVhPpX+sNf8fNxWaLu
  projectId: 3NKPCBVTU7

server:
  port: 8088